### ISSUE TITLE
Feature request: simplify command

### ISSUE THREAD

**Issue by JorgenStenshaugen** [DekodeInteraktiv/anonymize-mysqldump#20]
I currently use a really simple bash script for this, but would be nice to have it out of the box.

The script allows me to just type `anonymize filename.sql --config="path-to-config" --zip` and it runs the anonymizer script and compresses the outputted sql file

instead of doing all this:
`cat filename.sql | anonymize-mysqldump --config "anonymize.config.json" > "filename_anonymized.sql";`
`tar -czvf "filename_anonymized.tar.gz" "filename_anonymized.sql" && rm -rf "filename_anonymized.sql"`

**Comment by Clorith** [comment]
This is more about personal workflow, and not specifically about the anonymizer tools own commands, will as such be closing as wontfix for this repos intent and purpose.
