### ISSUE TITLE
Allow defining faker locale in the config file

### ISSUE THREAD

**Issue by PeterBooker** [DekodeInteraktiv/anonymize-mysqldump#34]
Recording the suggestion here (props Marius J). It would be great to allow the config file to define the faker locale.

We just need to decide which takes precedence between the CLI flag and the config?

**Comment by Clorith** [comment]
CLI flag should always take priority, as it's intentional user definitions at runtime.

**Comment by Clorith** [comment]
Fixed in 43682d37a1abaaebaa106cb1022743ce05d93b91
